Add input labels to Login & Signup pages
uwblueprint/building-up-client pull request #62
Opened 2021-04-20 18:08 UTC by patrick-du

## Description

Link to ticket: https://www.notion.so/uwblueprintexecs/Add-labels-to-inputs-log-in-page-f02c4e3418464a2f9d986c8ba134bf0c

I removed the placeholders because I thought it looked odd but I can put it back if we want both label and placeholder.

2021-04-20 23:11 UTC, jzxhuang reviewed
hmm, placeholders look ok to me in the [Figma mock ](https://www.figma.com/file/s6xLJftM99Xto7FW9AAtGU/Building-Up---Dashboard?node-id=2349%3A753).

I'm pretty indifferent, you can ask designers if you want I guess. otherwise code looks good

2021-04-21 01:53 UTC, patrick-du commented
> hmm, placeholders look ok to me in the [Figma mock ](https://www.figma.com/file/s6xLJftM99Xto7FW9AAtGU/Building-Up---Dashboard?node-id=2349%3A753).
> 
> I'm pretty indifferent, you can ask designers if you want I guess. otherwise code looks good

Oh, the placeholders were just "Email" and "Password" before - this looks better.

2021-04-21 03:37 UTC, jzxhuang requested changes

2021-04-21 03:37 UTC, jzxhuang commented on src/components/dashboard/LoginRegister/RegisterInput.js
> +            isRequired
```suggestion
            isRequired
            minLength={8}
```

apparently this attribute exists, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text, may as well add it while we're at it

2021-04-21 03:37 UTC, jzxhuang commented on src/components/dashboard/LoginRegister/RegisterInput.js
> +            placeholderonChange={onChangeFirstName}
```suggestion
            onChange={onChangeFirstName}
```

2021-04-21 03:42 UTC, jzxhuang approved these changes

2021-04-21 03:42 UTC, merged